repos:
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      name: isort
      args: ["--profile", "black", "--line-length", "79", "--multi-line", "3", "--filter-files"]
- repo: https://github.com/psf/black
  rev: 21.4b2
  hooks:
    - id: black
      language_version: python3.8
      args: ["--line-length", "79"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
    - id: mypy
      # Since mypy runs in an isolated virtualenv, we may need to add some dependencies
      additional_dependencies:
      - 'pydantic'
      - 'fastapi'
      - 'fastapi-pagination'
      - 'pytest-asyncio'
