# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy vax-availability-api

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.6

    - name: Install dependencies
      run: poetry install

    - name: Run linters (mypy, black, isort)
      run: |
       poetry run mypy --config-file mypy.ini .
       poetry run black --line-length 79 --check .
       poetry run isort --profile black --line-length 79 --multi-line 3 \
         --filter-files --check --diff .

  BuildDocker:
    runs-on: 'ubuntu-latest'
    needs: BuildAndTest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/vax-hunters-api:${{ github.sha }}
        file: ./Dockerfile

  DeployStaging:
    runs-on: ubuntu-latest
    needs: BuildDocker
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp-staging.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App (staging)
      id: deploy-to-webapp-staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vax-availability-api-staging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/vax-hunters-api:${{ github.sha }}'

  DeployProduction:
    runs-on: ubuntu-latest
    needs: DeployStaging
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App (production)
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vax-availability-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/vax-hunters-api:${{ github.sha }}'

