CREATE TABLE [dbo].[location_keys](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[location] [int] NULL,
	[key] [uniqueidentifier] NULL,
 CONSTRAINT [PK__location__3213E83F374B2C6C] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]